# Generated by Django 5.2.8 on 2025-12-02 15:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='expenses',
            new_name='Expense',
        ),
        migrations.RenameModel(
            old_name='userSettings',
            new_name='userSetting',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='tags',
            new_name='tag',
        ),
    ]
