# Generated by Django 5.2.8 on 2025-12-08 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_rename_expenses_expense_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='desc',
            new_name='description',
        ),
    ]
