import React from 'react';

const InsightsPanel = ({ loading, insightText }) => {
    return (
        <div className="panel ai-insights-panel">
            <div className="ai-badge">
                <svg className="ai-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                    <path d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" />
                </svg>
                <span>AI Powered</span>
            </div>
            <div className="panel-header">
                <h2 className="panel-title ai-title">
                    <span className="ai-gradient-text">Smart Insights</span>
                </h2>
                <span className="panel-caption">
                    Personalized analysis powered by Google Gemini AI
                </span>
            </div>
            {loading ? (
                <div className="ai-loading">
                    <div className="ai-loading-animation">
                        <div className="ai-pulse"></div>
                        <div className="ai-pulse"></div>
                        <div className="ai-pulse"></div>
                    </div>
                    <span>AI is analyzing your spending patterns...</span>
                </div>
            ) : insightText ? (
                <div className="ai-insight-content">
                    <div className="ai-insight-text">{insightText}</div>
                    <div className="ai-footer">
                        <svg className="ai-footer-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                            <circle cx="12" cy="12" r="3" />
                            <path d="M12 1v6m0 6v6" />
                            <path d="m15.5 3.5-1.5 1.5" />
                            <path d="m10 12 1.5 1.5" />
                            <path d="m15.5 20.5-1.5-1.5" />
                            <path d="M4 12l2-2" />
                            <path d="M20 12l-2-2" />
                            <path d="m4.5 5.5 2 2" />
                            <path d="m18.5 5.5-2 2" />
                            <path d="m18.5 18.5-2-2" />
                            <path d="m4.5 18.5 2-2" />
                        </svg>
                        <span>Generated by AI • Powered by Google Gemini</span>
                    </div>
                </div>
            ) : (
                <div className="ai-empty-state">
                    <div className="ai-empty-icon">
                        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                            <path d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" />
                        </svg>
                    </div>
                    <p>AI insights will appear here when there is enough spending data to analyze.</p>
                    <span className="ai-empty-caption">Add more expenses to unlock personalized insights!</span>
                </div>
            )}
        </div>
    );
};

export default InsightsPanel;
